release/major: ['breaking/*', 'major/*', 'maj/*']
release/minor: ['feature/*', 'feat/*', 'minor/*', 'min/*']
release/patch: ['bug/*', 'fix/*', 'patch/*', 'chore/*', 'update/*', 'deps/*', dockerfile-updater/*]
